---
title: "TCC MBA USP/ESALQ"
author: "Ivaney Vieira de Sales"
date: "01/02/2022"
output:
html_document:
highlight: kate
theme: paper
toc: yes
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```
# Classificação de estabelecimentos concorrentes
## Carga de pacotes
```{r Carga de Pacotes }
pacotes <- c("tidyverse", "ggmap", "kableExtra", "sjPlot")

if (sum(as.numeric(!pacotes %in% installed.packages())) != 0) {
  instalador <- pacotes[!pacotes %in% installed.packages()]
  for (i in seq_along(instalador)) {
    install.packages(instalador, dependencies = T)
    break() }
  sapply(pacotes, require, character = T)
} else {
  sapply(pacotes, require, character = T)
}
```
## Funções uteis
```{r Funções uteis}
tabelaContgenciaCNAE <- function(df, cnae01, cnae02) {
  rows <- df[paste0("cnae", cnae01)]
  cols <- df[paste0("cnae", cnae02)]
  sjt.xtab(title = paste0("Tabela de Contigencia ente os CNAE ", cnae01, "x", cnae02),
           var.row = rows,
           var.col = cols,
           variableLabels = c(cnae01, cnae02),
           show.exp = TRUE,
           show.row.prc = TRUE,
           show.col.prc = TRUE)
}

tabela <- function(df, caption = "") {
  df %>%
    kable(caption = caption) %>%
    kable_styling(bootstrap_options = "striped",
                  full_width = TRUE,
                  font_size = 12)
}

strTable <- function(df, caption = "") {
  data.frame(variable = names(df),
             classe = sapply(df, typeof),
             first_values = sapply(df, function(x) paste0(head(x), collapse = ", ")),
             row.names = NULL) %>%
    tabela(caption = caption)
}
```
## Carga e processamento da base de estabelecimentos

Será feia a carga do arquivo estabelecimento.txt. Este arquivo contem informação sobre os estabelecimentos da cidade de Teresna concorrente da Pintos LTDA.
```{r Carga e Processamento de estabelecimento}
df.estabelacimento.bruto <- read.csv("estabelecimentos.txt", sep = ";", dec = ",",
                                     colClasses = c("CNPJ_BASICO" = "character", "CNPJ_ORDEM" = "character", "CNPJ_DV" = "character",
                                                    "IDENTIFICADOR_MF" = "integer", "NOME_FANTASIA" = "character", "SITUACAO" = "integer",
                                                    "DATA_SITUACAO" = "character", "MOTIVO_SITUACAO" = "integer", "CIDADE_EXT" = "character",
                                                    "PAIS" = "integer", "DATA_ATIVIDADE" = "character", "CNAE_PRINCIPAL" = "integer",
                                                    "CNAE_SECUNDARIO" = "character", "TIPO_LOG" = "character", "LOGRADOURO" = "character",
                                                    "NUMERO" = "character", "COMPLEMENTO" = "character", "BAIRRO" = "character",
                                                    "CEP" = "character", "UF" = "factor", "MUNICIPIO" = "integer",
                                                    "DDD1" = "character", "TELEFONE1" = "character", "DDD2" = "character",
                                                    "TELEFONE2" = "character", "DDD_FAX" = "character", "FAX" = "character",
                                                    "EMAIL" = "character", "SITUACAO_ESPECIAL" = "character", "DATA_SITUACAO_ESPECIAL" = "integer",
                                                    "RAZAO_SOCIAL" = "character", "NATUREZA" = "integer", "QUALICACAO_RESPONSAVEL" = "integer",
                                                    "CAPITAL" = "numeric", "PORTE" = "integer", "ENTE_FED_RESPONSAVEL" = "character"
                                     ))

df.estabelacimento <- df.estabelacimento.bruto %>%
  transmute(
    cnpj = paste0(CNPJ_BASICO, CNPJ_ORDEM, CNPJ_DV),
    nome = NOME_FANTASIA,
    tipo = if_else(.$IDENTIFICADOR_MF == 1, 'MATRIZ',
                   if_else(.$IDENTIFICADOR_MF == 2, 'FILIAL', NULL)),
    situacao = if_else(.$SITUACAO == 1, "NULA",
                       if_else(.$SITUACAO == 2, "ATIVA",
                               if_else(.$SITUACAO == 3, "SUSPENSA",
                                       if_else(.$SITUACAO == 4, "INAPTA",
                                               if_else(.$SITUACAO == 8, "BAIXADA",
                                                       NULL))))),
    dataSituacao = .$DATA_SITUACAO %>% as.Date(format = "%Y%m%d"),
    dataAtividade = .$DATA_ATIVIDADE %>% as.Date(format = "%Y%m%d"),
    cnaePrincipal = .$CNAE_PRINCIPAL,
    cnaeSecundario = .$CNAE_SECUNDARIO %>% str_split(","),
    endereco = paste0(.$TIPO_LOG, " ", .$LOGRADOURO, ", ", .$COMPLEMENTO, " ", .$NUMERO, " - ",
                      .$BAIRRO, ", TERESINA - PI, "),
    cep = CEP,
    razaoSociao = RAZAO_SOCIAL,
    capital = CAPITAL,
    porte = if_else(.$PORTE == 0, "NÂO INFORMADO",
                    if_else(.$PORTE == 1, "MICRO EMPRESA",
                            if_else(.$PORTE == 3, "PEQUENO PORTE",
                                    if_else(.$PORTE == 5, "DEMAIS", NULL))))
  )

df.estabelacimento <- df.estabelacimento %>% add_column(
  cnaes = mapply(list, .$cnaePrincipal, .$cnaeSecundario, SIMPLIFY = F) %>% map(unlist)
)
```
## Data frame de estabelecimentos
```{r}
df.estabelacimento %>% strTable("Estabelecimento")
```
