/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package maps

import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.firefox.FirefoxDriverService

fun main() {
    val driver = FirefoxDriver()
    driver.navigate()
    driver.setW
}
